version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Go vet tool
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - gocritic      # Comprehensive linter with many checks
    - revive        # Fast, configurable, extensible, flexible linter
    - misspell      # Find commonly misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - bodyclose     # Check if HTTP response body is closed
    - errname       # Check error naming conventions
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - gosec         # Security-oriented linter
    - nilerr        # Find code that returns nil error but non-nil error value
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - commentFormatting
        - whyNoLint
    revive:
      rules:
        - name: exported
          disabled: false
        - name: package-comments
          disabled: true
